---
- name: Install Java
  hosts: all  # Replace with your actual host group or IP address
  become: yes  # Run tasks with root privileges
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk  # Install OpenJDK 11 JDK package
        state: present         # Ensure the package is present

    # Optionally, you can add tasks here to set environment variables or configure Java options as needed
